before_script:
  - docker info

build_image:
  script:
    - docker build -t spoonerweb/gitlab-auto-merge-request .
    - echo ${DOCKER_PASSWORD} | docker login -u spoonerweb --password-stdin
    - docker push spoonerweb/gitlab-auto-merge-request
  tags:
    - docker-build
